package az.codeworld.springboot.aop.validations;

import jakarta.validation.Constraint;
import jakarta.validation.Payload;
import java.lang.annotation.Documented;
import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

import az.codeworld.springboot.aop.validators.UsernameValidator;

@Documented
@Constraint(validatedBy = UsernameValidator.class) 
@Target({ ElementType.FIELD, ElementType.METHOD, ElementType.PARAMETER })
@Retention(RetentionPolicy.RUNTIME)                
public @interface UsernameValidation {

    String message() default "Invalid username!, Username is auto-generated by the system in the format of : ^[STA]-[A-Z0-9]{4}-[A-Z0-9]{4}-\\\\d{1,}$";     

    Class<?>[] groups() default {};               

    Class<? extends Payload>[] payload() default {};
}
